project:
  type: website
  output-dir: docs

website:
  title: "SIH Introduction to Version Control using Git"
  navbar:
    background: primary
    left:
      - href: index.html
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "Session 1"
        menu:
        - text: "Introduction to version control"
          href: notebooks/01_intro.html
        - text: "Configure git"
          href: notebooks/02_config.html
        - text: "Creating a repository"
          href: notebooks/03_create.html
        - text: "Making changes"
          href: notebooks/04_changes.html
        - text: "Seeing history"
          href: notebooks/05_history.html
        - text: "Ignoring files"
          href: notebooks/06_ignore.html
        - text: "Pushing to GitHub"
          href: notebooks/07_github.html
        - text: "Collaborating"
          href: notebooks/08_collab.html
      - text: "Session 2"
        menu:
        - text: "Branching"
          href: notebooks/09_branches.html
        - text: "Merging"
          href: notebooks/10_merging.html
        - text: "Branches and workflows"
          href: notebooks/11_workflows.html
        - text: "Pull requests"
          href: notebooks/12_pull_requests.html
        - text: "Conflicts"
          href: notebooks/13_conflicts.html
        - text: "Open research"
          href: notebooks/14_open_research.html


  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"
          
format:
  html:
    theme: simplex
    css: lesson.css
    toc: true
    code-overflow: wrap
    highlight-style: github

