project:
  type: website
  output-dir: docs

website:
  title: "SIH Introduction to version control using git"
  navbar:
    background: primary
    left:
      - href: index.html
        text: Home
      - href: setup.html
        text: "Setup"
      - text: "Session 1"
        menu:
        - text: "Fundamentals"
          href: notebooks/01_intro.html

  body-footer: "All materials copyright Sydney Informatics Hub, University of Sydney"
          
format:
  html:
    theme: simplex
    css: lesson.css
    toc: true
    code-overflow: wrap
    highlight-style: github

