---
title: "SIH Introduction to version control using git"
output:
  html_document:
    toc: false
    toc_float: false
---


This course is aimed at researchers, students, and industry professionals who want to learn about version controlling their code (or text files). 

This course is adapted from [Version Control with Git](https://swcarpentry.github.io/git-novice) by staff from the Sydney Informatics Hub (Darya Vanichkina, ...). 


## Trainers

* Darya Vanichkina (PhD Bioinformatics, SFHEA)
* Kristian Maras (MSc Quant Fin)
* Nathaniel (Nate) Butterworth (PhD Computational Geophysics)
* Michael Lynch (Research Software Engineering Team Lead)

## Course pre-requisites and setup requirements

- No previous programming experience is required.
- Training will be delivered in-person, so you will need your own laptop with a stable internet connection and the ability to install your own software.

## Code of Conduct
We expect all attendees of our training to follow our code of conduct, including bullying, harassment and discrimination prevention policies.

In order to foster a positive and professional learning environment we encourage the following kinds of behaviours at all our events and on our platforms:

* Use welcoming and inclusive language
* Be respectful of different viewpoints and experiences
* Gracefully accept constructive criticism
* Focus on what is best for the community
* Show courtesy and respect towards other community members

Our full CoC, with incident reporting guidelines, is available [here](https://sydney-informatics-hub.github.io/codeofconduct/).

## Setup Instructions

Please complete the [Setup Instructions](./setup.html) **before the course**.

If you have any trouble, please get in contact with us via email ASAP. 
